### ISSUE TITLE
AMQP (RabbitMQ) and trade replicator

### ISSUE THREAD

**Issue by femtotrader** [kr0st/trade_replicator#2]
Hello,

I'd like to have a trade replicator but I wonder if a messaging queue such as RabbitMQ (AMQP) https://www.rabbitmq.com/getstarted.html is not something you should consider

AMQP http://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol

What is your opinion about that ?

Kind regards

Femto

**Comment by kr0st** [comment]
So, even physics professors are interested in trading it seems :) Well, all those queuing solutions including ZeroMQ (http://zeromq.org/) are quite fast and interesting although usually they themselves use some NoSQL solution underneath.

Do you really need queue or just a fast storage? In case of a fast storage you definitely should look at some NoSQL stuff or just super simple key-value stores like MemCached or https://en.wikipedia.org/wiki/Kyoto_Cabinet

For this trade replicator implementation such speed is not needed because using MT4 clients and MQL definitely puts MT4 solution out of high-frequency trading for sure. If you need something fast then a direct access to trading API is needed, for example you pay to get FIX protocol access to a certain trading platform then you can have much faster order flow.

My trade replicator is not targeted at really high speed trading and I have no intentions / interest to change that.
